### ISSUE TITLE
Compiler error when updating to new version of plugin

### ISSUE THREAD

**Issue by Frozenfire92** [ouya/ouya-unity-plugin-old#13]
Unity 4.3.4

Imported the core package into my project and got this

Assets/Ouya/SDK/Scripts/OuyaGameObject.cs(20,7): error CS0246: The type or namespace name `OuyaSDK_LitJson' could not be found. Are you missing a using directive or an assembly reference?

**Comment by tgraupmann** [comment]
Ah I may need to update the package export for Core to pickup the moved LitJson files.

**Comment by Frozenfire92** [comment]
see https://github.com/ouya/ouya-unity-plugin/pull/14
