### ISSUE TITLE
Wrong path of classes.jar in Unity 4.5

### ISSUE THREAD

**Issue by cesarvarela** [ouya/ouya-unity-plugin-old#18]
In unity 4.5  the new path for the `classes.jar` of the AndroidPlayer is:

`/Contents/PlaybackEngines/AndroidPlayer/release/bin/classes.jar`

And OuyaPanel is looking for it in:

`Contents/PlaybackEngines/AndroidPlayer/bin/classes.jar`

**Comment by tgraupmann** [comment]
This is the legacy plugin. You'll find the new plugin compatible with Unity 4.5 here:
https://github.com/ouya/ouya-sdk-examples/releases

**Comment by cesarvarela** [comment]
Ups my bad, I'll close this one.
