### ISSUE TITLE
Game works on Unity 4.3, crashes on 4.5

### ISSUE THREAD

**Issue by cesarvarela** [ouya/ouya-unity-plugin-old#19]
All this running in the editor, without trying to debug, just hitting play hangs Unity 4.5 and I have to manually kill Unity.

I'll use Unity 4.3 for the OUYA release, but you guys might wanna give it a look.

**Comment by tgraupmann** [comment]
Give the new plugin a try and let me know how it goes.

https://github.com/ouya/docs/blob/master/ouya-everywhere-unity/ouya-everywhere-unity.md

**Comment by cesarvarela** [comment]
Ok so the plugin had nothing to do with the crashes, it was a bug in the new Unity, related to having a PS3 joystick connected to the :apple: 

http://www.reddit.com/r/Unity3D/comments/27ju5a/unity_451_is_now_available_first_minor_update_to/

Thanks!
