### ISSUE TITLE
Missing IFetchGamerUUIDListener

### ISSUE THREAD

**Issue by Adamcbrz** [ouya/ouya-unity-plugin-old#2]
I just pulled down the complete package and I am getting errors in unity dealing with OuyaSDK not containing IFetchGamerUUIDListener or any of the methods in references to those items. Since that appears to be the last commit I am assuming that the OuyaSDK.cs was not commited with the changes.

Exact Error:
Assets/Ouya/Examples/Scripts/OuyaShowProducts.cs(22,13): error CS0426: The nested type `IFetchGamerUUIDListener' does not exist in the type`OuyaSDK'

**Comment by tgraupmann** [comment]
Checked in try that now... Thanks for the heads up. I moved OuyaSDK to the Assets/Plugins folder to be available to JavaScript and missed it in the checkin. It should be good to go now.

**Comment by Adamcbrz** [comment]
Working now thank you.
