### ISSUE TITLE
LitJson could not be found

### ISSUE THREAD

**Issue by jefreestyles** [ouya/ouya-unity-plugin-old#20]
Assets/Ouya/SDK/Scripts/OuyaGameObject.cs(20,7): error CS0246: The type or namespace name `LitJson' could not be found. Are you missing a using directive or an assembly reference?

I'm receiving this message when trying to build using both the Core and StartKit Unity Packages.

I have the latest version of the OuyaSDK from git with the updated code:
From Assets/Litjson to Assets/Ouya/Litjson.

**Comment by tgraupmann** [comment]
You'll actually find the latest plugin in OUYA-Everywhere which I've removed the dependency on Litjson.
https://github.com/ouya/docs/blob/master/ouya-everywhere-unity/ouya-everywhere-unity.md
