### ISSUE TITLE
Incorrect log message in OuyaUnityPlugin.java

### ISSUE THREAD

**Issue by omgwtfgames** [ouya/ouya-unity-plugin-old#7]
Line 314 in current master: https://github.com/ouya/ouya-unity-plugin/blob/master/Assets/Plugins/Android/src/OuyaUnityPlugin.java#L314

Log message "OuyaUnityPlugin.getReceiptsAsync" should be "OuyaUnityPlugin.getProductsAsync"

Similar issue on lines 411 and 448.

Trivial, but something that could cause confusion.

**Comment by tgraupmann** [comment]
Corrected. Thanks for the heads up. I do plan on doing more changes to be inline with the other engines. I.e. OuyaTestFacade will become UnityOuyaFacade.

**Comment by omgwtfgames** [comment]
Great - thanks for the quick fix !
